# Generated by Django 4.2.17 on 2024-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="기본방", max_length=180),
        ),
    ]
