# Generated by Django 4.2.17 on 2024-12-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=180),
        ),
    ]
