databases:
  - name: airbnbclone-db
    plan: free
    databaseName: airbnbclone_kbor
    user: airbnbclone
    region: singapore

services:
  - type: web
    plan: free
    name: airbnb-back
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone_kbor
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
