# Generated by Django 4.2.17 on 2024-12-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
