# Generated by Django 4.2.17 on 2024-12-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_address_alter_experience_city_and_more"),
        ("reviews", "0002_alter_review_experience_alter_review_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="experiences.experience",
            ),
        ),
    ]
