# Generated by Django 4.2.17 on 2024-12-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_photo",
            new_name="avatar",
        ),
    ]
