# Generated by Django 4.2.17 on 2024-12-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_category_alter_experience_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="city",
            field=models.CharField(default="Seoul", max_length=80),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(default="Korea", max_length=50),
        ),
        migrations.AlterField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
